name: Run Tests on Multiple OS

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.1

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
      shell: pwsh

    - name: Run pytest
      run: pytest
