name: Run Pytest on Push

on:
  push:
    branches:
      - '**'  # Triggers the workflow on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade
