name: Run Pytest on Push

on:
  push:
    branches:
      - '**'  # Triggers the workflow on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pytest
      run: pytest
